#!/usr/bin/env python3
import sqlite3
from datetime import datetime
from pathlib import Path

# Connect to database
db_path = Path('/Users/bobvarkey/.openclaw/workspace/memory_x_posts.db')
conn = sqlite3.connect(db_path)
cursor = conn.cursor()

# Get all posts
cursor.execute('''
    SELECT author_name, handle, datetime, text, likes, reposts, replies, views, url, search_query
    FROM posts
    ORDER BY CAST(likes AS INTEGER) DESC
''')
all_posts = cursor.fetchall()

# Get high-engagement posts (>= 50 likes)
cursor.execute('''
    SELECT author_name, handle, datetime, text, likes, reposts, replies, views, url, search_query
    FROM posts
    WHERE CAST(likes AS INTEGER) >= 50
    ORDER BY CAST(likes AS INTEGER) DESC
''')
high_engagement = cursor.fetchall()

# Get stats by query
cursor.execute('''
    SELECT search_query, COUNT(*) as count
    FROM posts
    GROUP BY search_query
''')
query_stats = cursor.fetchall()

# Create markdown report
report_date = '2026-05-22'  # As requested in the task
report_path = Path(f'/Users/bobvarkey/.openclaw/workspace/knowledge-base/x-scrapes/x-scrape-{report_date}.md')

md_content = f"""# X/Twitter Scrape Report - {report_date}

Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

## Summary

- **Total Posts Scraped:** {len(all_posts)}
- **High-Engagement Posts (≥50 likes):** {len(high_engagement)}

### Posts by Search Query

"""

for query, count in query_stats:
    md_content += f"- **{query}**: {count} posts\n"

md_content += "\n## High-Engagement Posts (≥50 likes)\n\n"

for post in high_engagement:
    author, handle, date, text, likes, rt, replies, views, url, query = post
    
    md_content += f"### {author} {handle}\n\n"
    md_content += f"**Date:** {date}\n\n"
    md_content += f"**Engagement:** {likes} likes, {rt} retweets, {replies} replies\n\n"
    md_content += f"**Text:** {text[:200]}{'...' if len(text) > 200 else ''}\n\n"
    md_content += f"**URL:** {url}\n\n"
    md_content += f"**Search Query:** {query}\n\n"
    md_content += "---\n\n"

md_content += "## All Posts by Search Query\n\n"

# Group posts by query
posts_by_query = {}
for post in all_posts:
    query = post[9]
    if query not in posts_by_query:
        posts_by_query[query] = []
    posts_by_query[query].append(post)

for query in sorted(posts_by_query.keys()):
    posts = posts_by_query[query]
    md_content += f"### Query: {query}\n\n"
    md_content += f"**Total Posts:** {len(posts)}\n\n"
    
    for post in posts:
        author, handle, date, text, likes, rt, replies, views, url, _ = post
        
        md_content += f"#### {author} {handle}\n\n"
        md_content += f"- **Date:** {date}\n"
        md_content += f"- **Likes:** {likes} | **RT:** {rt} | **Replies:** {replies}\n"
        md_content += f"- **Text:** {text[:150]}{'...' if len(text) > 150 else ''}\n"
        md_content += f"- **URL:** {url}\n\n"

md_content += f"""
---

*Report generated by X/Twitter scraper on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*
"""

# Write report
with open(report_path, 'w') as f:
    f.write(md_content)

print(f"Report generated: {report_path}")
print(f"\nSummary:")
print(f"- Total posts: {len(all_posts)}")
print(f"- High-engagement posts (≥50 likes): {len(high_engagement)}")

# Print interesting/notable posts
print("\n## Notable High-Engagement Posts:")
for i, post in enumerate(high_engagement[:5], 1):
    author, handle, date, text, likes, rt, replies, views, url, query = post
    print(f"\n{i}. {author} {handle}")
    print(f"   Likes: {likes}, RT: {rt}, Replies: {replies}")
    print(f"   Text: {text[:100]}...")
    print(f"   URL: {url}")

conn.close()