#!/usr/bin/env python3
import sqlite3
from datetime import datetime

# Connect to database
conn = sqlite3.connect('/Users/bobvarkey/.openclaw/workspace/memory_x_posts.db')
cursor = conn.cursor()

# Get all posts
posts = cursor.execute('''
    SELECT author, handle, text, date, likes, reposts, replies, url, search_term
    FROM x_posts
    ORDER BY date DESC
''').fetchall()

# Get high engagement posts
high_posts = cursor.execute('''
    SELECT author, handle, text, date, likes, reposts, replies, url
    FROM x_posts
    WHERE likes > 50
    ORDER BY likes DESC
''').fetchall()

conn.close()

# Generate markdown report
report = """# X/Twitter Scrape Report - Neurointervention & Stroke

**Date:** {date}
**Scraped At:** {scraped_at}

## Summary

- **Total Posts:** {total}
- **High Engagement Posts (>50 likes):** {high_count}
- **Search Terms Used:**
  1. neurointervention OR thrombectomy OR #Neurointervention OR #stroke
  2. cerebral AVM OR intracranial aneurysm OR endovascular

## High Engagement Posts (>50 likes)

{high_engagement_section}

## All Posts

{all_posts_section}

---

*Report generated by OpenClaw X/Twitter Scraper*
"""

# Format date
now = datetime.now()
date_str = now.strftime("%Y-%m-%d %H:%M:%S IST")

# Build high engagement section
high_section = ""
if high_posts:
    for i, (author, handle, text, date, likes, reposts, replies, url) in enumerate(high_posts, 1):
        high_section += f"""
### {i}. {author} {handle}

- **Likes:** {likes}
- **Reposts:** {reposts}
- **Replies:** {replies}
- **Date:** {date}
- **URL:** [{url}]({url})

**Text:**
> {text}

---

"""
else:
    high_section = "No posts with >50 likes found.\n"

# Build all posts section
all_section = ""
for i, (author, handle, text, date, likes, reposts, replies, url, search_term) in enumerate(posts, 1):
    all_section += f"""
### {i}. {author} {handle}

- **Likes:** {likes} | **Reposts:** {reposts} | **Replies:** {replies}
- **Date:** {date}
- **URL:** [{url}]({url})
- **Search Term:** {search_term}

**Text:** {text}

---

"""

# Fill in the template
report = report.format(
    date=date_str,
    scraped_at=date_str,
    total=len(posts),
    high_count=len(high_posts),
    high_engagement_section=high_section,
    all_posts_section=all_section
)

# Write to file
output_file = '/Users/bobvarkey/.openclaw/workspace/knowledge-base/x-scrapes/x-scrape-2026-07-13.md'
with open(output_file, 'w') as f:
    f.write(report)

print(f"Report saved to: {output_file}")
print(f"\nTotal posts: {len(posts)}")
print(f"High engagement posts (>50 likes): {len(high_posts)}")