-- Posts from search 1: neurointervention OR thrombectomy OR #Neurointervention OR #stroke
INSERT INTO x_posts (author, handle, date, text, likes, reposts, replies, bookmarks, views, url, search_query) VALUES
-- Posts from Latest tab (June 28, 2026)
('Nick Clarke', '@69Clarkey', '2026-06-28', '#Stroke', 0, 0, 0, 0, 1, 'https://x.com/69Clarkey/status/2071208561770738065', 'neurointervention OR thrombectomy OR #Neurointervention OR #stroke'),
('James Bundy', '@jamesbundy', '2026-06-28', 'We need 24/7 thrombectomy in our country.', 0, 0, 0, 0, 77, 'https://x.com/jamesbundy/status/2071190622736642493', 'neurointervention OR thrombectomy OR #Neurointervention OR #stroke'),
('Hemostasis Today', '@HemostasisToday', '2026-06-28', 'Can Mechanical Thrombectomy Be Safely Used in Cervical Artery Dissection? - Francesco Favruzzo @m_paciaroni @ZiniAndrea @PietroCali1905 hemostasistoday.com/science/france #HemostasisToday', 0, 0, 0, 0, 9, 'https://x.com/HemostasisToday/status/2071179300162728428', 'neurointervention OR thrombectomy OR #Neurointervention OR #stroke'),
('SFC - Société Française de Cardiologie', '@SFCardio', '2026-06-27', 'Phone-Based Intervention Under Nurse Guidance for Control of Hypertension After Stroke: A Randomized Multicenter Phase 3 Trial in Ghana (Circulation, April 2026) 🔗 doi.org/10.1161/CIRCUL #CardioTwitter #Hypertension #Stroke #PINGS', 1, 1, 0, 1, 176, 'https://x.com/SFCardio/status/2070872527736652016', 'neurointervention OR thrombectomy OR #Neurointervention OR #stroke'),
('@RadiologyEditor', '@RadiologyEditor', '2026-06-27', 'Quick weekend catch-up in #Radiology 👀 AI breast cancer risk trends, cardiac MRI for HF prediction, spinal degeneration insights, thrombectomy in complex stroke, and AI‑enhanced MR lymphangiography. ⬇️ ⬇️ Take a look ⬇️ ⬇️ pubs.rsna.org/toc/radiology/', 0, 0, 0, 0, 182, 'https://x.com/RadiologyEditor/status/2070860196352819432', 'neurointervention OR thrombectomy OR #Neurointervention OR #stroke'),
('Axon Stroke & Spine Center', '@axon_stroke', '2026-06-27', 'የስትሮክ እና ሌሎች የደም ስር እክሎች (vascular malformations) ህክምና በስተጀርባ ያለው አስደናቂ ቴክኖሎጂ ምን እንደሆነ ያውቃሉ? ቪዲዮውን ይመልከቱ። +251-111-136140 #AxonStrokeAndSpineCenter #Cathlab #Stroke #Ethiopia #AddisAbaba', 0, 0, 0, 0, 49, 'https://x.com/axon_stroke/status/2070824461683527997', 'neurointervention OR thrombectomy OR #Neurointervention OR #stroke'),
('Dr. H V Satish Babu | Neurosurgeon | Bangalore', '@drhvsbabu', '2026-06-27', 'A stroke is a medical emergency—every minute counts. Early diagnosis and timely treatment can reduce complications and improve recovery. 🌐 ColumbiaaHospital.com | DrHVSatishBabu.com #StrokeAwareness #Stroke #BrainHealth #FAST #ColumbiaaHospital #DrHVSatishBabu', 0, 0, 0, 0, 8, 'https://x.com/drhvsbabu/status/2070797701688721586', 'neurointervention OR thrombectomy OR #Neurointervention OR #stroke'),
('Columbiaa Hospital', '@columbiaahosp', '2026-06-27', 'A stroke is a medical emergency—every minute counts. Early diagnosis and timely treatment can reduce complications and improve recovery. 🌐 ColumbiaaHospital.com | DrHVSatishBabu.com #StrokeAwareness #Stroke #BrainHealth #FAST #ColumbiaaHospital #DrHVSatishBabu', 0, 0, 0, 0, 5, 'https://x.com/columbiaahosp/status/2070797631455207534', 'neurointervention OR thrombectomy OR #Neurointervention OR #stroke'),
('Annals of Indian Academy of Neurology', '@AnnIndAcadNeur', '2026-06-27', '@drayushagarwal et al published a case of hepatitis B associated aorto-arteritis highlighting that infection-related strokes, although rare, are an important etiology of stroke in young #Strokeinyoung #stroke @neuro_ian @Divyani_Garg @achalaiims Link: 10.4103/aian.aian_351_26', 15, 8, 0, 1, 482, 'https://x.com/AnnIndAcadNeur/status/2070784324811857930', 'neurointervention OR thrombectomy OR #Neurointervention OR #stroke'),
-- Posts from Top tab
('Neurology Journal', '@GreenJournal', '2026-06-12', 'Neurology Podcast: Dr. Dan Ackerman and Dr. Reza Bavarsad Shahripour discuss the diagnostic performance of 4 major modalities: TCD, TTE, TEE, and cardiac CT in patients with #EmbolicStroke of undetermined source. Listen now: hubs.la/Q04l5L0Q0 #Stroke', 23, 6, 2, 7, 4161, 'https://x.com/GreenJournal/status/2065190115090042937', 'neurointervention OR thrombectomy OR #Neurointervention OR #stroke'),
('Crémieux', '@cremieuxrecueil', '2026-06-27', 'The medical community has cured a mountain of diseases in the past several decades. Diseases cured thread 🧵 In 2013, hepatitis C was cured by direct-acting antivirals.', 1925, 328, 46, 632, 174434, 'https://x.com/cremieuxrecueil/status/2070633895163212025', 'neurointervention OR thrombectomy OR #Neurointervention OR #stroke');

-- Posts from search 2: cerebral AVM OR intracranial aneurysm OR endovascular
INSERT INTO x_posts (author, handle, date, text, likes, reposts, replies, bookmarks, views, url, search_query) VALUES
-- Posts from Top tab
('Nimer Abushehab, MD', '@NimerAdeeb', '2026-06-15', 'Large arteriovenous malformation (AVM), Spetzler-Martin Grade III, in a young man presenting with seizures and headaches. No history of rupture. Angiography before surgery (Left) demonstrated a high-flow AVM with significant vascular steal, diverting flow from the anterior', 33, 4, 1, 3, 1402, 'https://x.com/NimerAdeeb/status/2066245815002108296', 'cerebral AVM OR intracranial aneurysm OR endovascular'),
('NEJM', '@NEJM', '2026-06-22', 'Original Article: Endovascular Therapy for Post-Thrombotic Syndrome — A Randomized Trial (phase 3 C-TRACT trial) nej.md/3QsqxJ2 Editorial: Stenting for Post-Thrombotic Syndrome — A Step Forward nej.md/4mhaFoJ #Surgery #Cardiology', 45, 16, 0, 7, 11974, 'https://x.com/NEJM/status/2068770979409539426', 'cerebral AVM OR intracranial aneurysm OR endovascular'),
-- Posts from Latest tab
('Hemostasis Today', '@HemostasisToday', '2026-06-28', 'A Safer Approach to Antiplatelet Timing in Endovascular Aneurysm Treatment - Gianluca De Rubeis hemostasistoday.com/science/gianlu #HemostasisToday', 0, 0, 0, 0, 10, 'https://x.com/HemostasisToday/status/2071186850228605413', 'cerebral AVM OR intracranial aneurysm OR endovascular'),
('Natalie Reed', '@natalreed', '2026-06-28', 'From ambassador to operating room: Eduardo Fonseca trades diplomacy for endovascular robots. yespress.io/eduardo-fonsec via Yespress', 0, 0, 0, 0, 5, 'https://x.com/natalreed/status/2071104871328080138', 'cerebral AVM OR intracranial aneurysm OR endovascular'),
('Dra. Yolanda Aburto Murrieta', '@yitaam73', '2026-06-28', 'Oclusión en tándem 🧠 Tandem Occlusion: A Challenge That Demands Strategy #InterventionalNeuroradiology #Endovascular #Ictus #TandemOcclusion #CarotidDissection #Neurovascular', 2, 0, 0, 0, 624, 'https://x.com/yitaam73/status/2071104848464957681', 'cerebral AVM OR intracranial aneurysm OR endovascular'),
('BaylisMedTech', '@BaylisMedTech', '2026-06-26', 'Make a big difference in small anatomy. The Passport Steerable Sheath''s D2 Model features our smallest 7mm curve bend—designed for accessing difficult to reach anatomy. Learn more: bit.ly/3Q9Mqcr #SteerableSheath #MedEd #IRad #TwittIR #VascTwitter #Endovascular', 0, 0, 0, 0, 21, 'https://x.com/BaylisMedTech/status/2070496516456763872', 'cerebral AVM OR intracranial aneurysm OR endovascular'),
('July', '@JulySeEs', '2026-06-26', 'Bundling, or in Spanish it would be like the packaging of supplies in endovascular vascular surgery at SeNaSa, is one of the most inhumane ideas for the patient and the most idiotic with regard to profitability… but, somehow, you have to "recover" the economic hole they created.', 14, 1, 0, 0, 1085, 'https://x.com/JulySeEs/status/2070491309131931974', 'cerebral AVM OR intracranial aneurysm OR endovascular'),
('Microbot', '@MicrobotMedical', '2026-06-26', 'Precision meets simplicity with the LIBERTY® Endovascular Robotic System. The only peripheral endovascular robotic system with a completely single-use, remote design. Learn more about LIBERTY®: hubs.ly/Q04m3yrx0 #Innovation #Robotics #InterventionalRadiology #MBOT', 14, 1, 0, 0, 400, 'https://x.com/MicrobotMedical/status/2070486069254979712', 'cerebral AVM OR intracranial aneurysm OR endovascular'),
('金やん', '@MZZxALW5qPiPmRv', '2026-06-26', 'Endovascular treatment is the first-line therapy.', 1, 0, 0, 0, 586, 'https://x.com/MZZxALW5qPiPmRv/status/2070469485203771873', 'cerebral AVM OR intracranial aneurysm OR endovascular'),
('Indian Pharma Post', '@indpharmapost', '2026-06-26', 'Microbot Medical wins surgical robotics industry award for LIBERTY Endovascular Robotic System indianpharmapost.com/medical-device #MicrobotMedical #robotic #endovascular @indpharmapost', 0, 0, 0, 0, 30, 'https://x.com/indpharmapost/status/2070465538766295247', 'cerebral AVM OR intracranial aneurysm OR endovascular');